# Production docker-compose.yml
# This file is automatically created by GitHub Actions on the server
# It's included here as reference/documentation

version: "3.9"

services:
  monstermemory:
    image: ghcr.io/olivermeimberg/io.meimberg.monstermemory:latest
    container_name: monstermemory
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5679
      - HOSTNAME=0.0.0.0
    labels:
      # Traefik automatic routing
      - "traefik.enable=true"
      - "traefik.http.routers.monstermemory.rule=Host(`monstermemory-2.meimberg.io`)"
      - "traefik.http.routers.monstermemory.entrypoints=websecure"
      - "traefik.http.routers.monstermemory.tls.certresolver=le"
      - "traefik.http.services.monstermemory.loadbalancer.server.port=5679"
    networks:
      - traefik

networks:
  traefik:
    external: true

