# Template for deploying apps with additional services (MySQL, Redis, etc.)
# Copy this file to .github/workflows/deploy-[APP_NAME].yml and customize

name: Deploy [APP_NAME] to Server

on:
  push:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/[APP_NAME]
  APP_PORT: ${{ vars.APP_PORT || '[APP_PORT]' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        npm run lint
        npm run build
        npm run test:ci

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./[APP_DIRECTORY]
        dockerfile: ./[APP_DIRECTORY]/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.HOST || secrets.HOST }}
        username: ${{ vars.USERNAME || 'deploy' }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # App-specific deployment with additional services
          APP_NAME="[APP_NAME]"
          APP_PORT="${{ env.APP_PORT }}"
          APP_DIR="/opt/$APP_NAME"
          
          # Create application directory
          mkdir -p $APP_DIR && cd $APP_DIR
          
          # Create docker-compose file with additional services
          cat > docker-compose.prod.yml << 'EOF'
          services:
            $APP_NAME:
              image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
              container_name: $APP_NAME
              ports:
                - "$APP_PORT:8080"
              environment:
                - NODE_ENV=production
                - PORT=8080
                # Database connection (if needed)
                - DB_HOST=mysql
                - DB_PORT=3306
                - DB_NAME=${{ vars.DB_NAME || 'appdb' }}
                - DB_USER=${{ vars.DB_USER || 'appuser' }}
                - DB_PASSWORD=${{ vars.DB_PASSWORD || 'apppassword' }}
                # Redis connection (if needed)
                - REDIS_HOST=redis
                - REDIS_PORT=6379
              depends_on:
                - mysql
                - redis
              restart: unless-stopped
              networks:
                - $APP_NAME-network
              healthcheck:
                test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s

            mysql:
              image: mysql:8.0
              container_name: ${APP_NAME}-mysql
              environment:
                - MYSQL_ROOT_PASSWORD=${{ vars.MYSQL_ROOT_PASSWORD || 'rootpassword' }}
                - MYSQL_DATABASE=${{ vars.DB_NAME || 'appdb' }}
                - MYSQL_USER=${{ vars.DB_USER || 'appuser' }}
                - MYSQL_PASSWORD=${{ vars.DB_PASSWORD || 'apppassword' }}
              volumes:
                - mysql_data:/var/lib/mysql
                - ./mysql-init:/docker-entrypoint-initdb.d
              restart: unless-stopped
              networks:
                - $APP_NAME-network
              healthcheck:
                test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
                interval: 30s
                timeout: 10s
                retries: 5

            redis:
              image: redis:7-alpine
              container_name: ${APP_NAME}-redis
              restart: unless-stopped
              networks:
                - $APP_NAME-network
              healthcheck:
                test: ["CMD", "redis-cli", "ping"]
                interval: 30s
                timeout: 10s
                retries: 3

          volumes:
            mysql_data:

          networks:
            $APP_NAME-network:
              driver: bridge
          EOF
          
          # Deploy
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml down || true
          docker-compose -f docker-compose.prod.yml up -d
          
          # Clean up
          docker image prune -f
          
          # Verify
          sleep 60  # Give more time for services to start
          if curl -f http://localhost:$APP_PORT/ > /dev/null 2>&1; then
            echo "✅ $APP_NAME deployed successfully on port $APP_PORT!"
            echo "📊 Services running:"
            docker-compose -f docker-compose.prod.yml ps
          else
            echo "❌ Deployment failed!"
            echo "📋 Service logs:"
            docker-compose -f docker-compose.prod.yml logs --tail=50
            exit 1
          fi

